### ISSUE TITLE
Requires a way to reset socket state

### ISSUE THREAD

**Issue by pylessard** [hartkopp/can-isotp#11] opened 2018-12-14 19:51 UTC
This issue is a mix of requirements and questions that arise maybe from my limited knowledge of the Linux kernel. I have been facing many times in the past a situation where I open many IsoTP socket and don't close them properly and end up not being able to use a specific socket address. 

Basically, I try to create a new socket using the same txid and rxid of the previous unclosed socket and the result is that I cannot changes its parameters (stmin, bs, wftmax) and reception is working interrmitently, (just like if 2 sockets were emptying the same buffer).

I know I created that problem by mishandling the sockets, but when that happens, I have found no other solution than rebooting my mahcine to clean that up. I've tried resetting the networking services, putting down/up the vcan interface, unloading the kernel module. None works.

Is there a way to reset the state of the kernel module?

**Comment by pylessard** [comment] 2018-12-14 20:26
I am closing this as I am still unsure if this problem is really related to the module.  I think I had a race conditions where 2 sockets were temporarily opened at the same time in different threads. I remember having similar issues in the past; I will reopen if I ever get concrete evidences that this issue is present.

**Comment by hartkopp** [comment] 2018-12-15 17:52
> Basically, I try to create a new socket using the same txid and rxid

This does not work by design!
Every endpoint needs a unique txid/rxid pair. If you open two sockets with the same txid/rxid pair (on the same host/interface) you get two **identical** state machines acting for the **same point-to-point** connection.

E.g. you send two FC frames to the sender (who will pick the first one an go for it).

**Comment by pylessard** [comment] 2018-12-15 20:33
I understand that this can't work. The goal here is to delete the previous socket before opening the new one. Seems that in some case, I can't do that. But as I said, I can't tell exactly how I get in this situation, so I believe this should be closed.

rmmod return "module is busy", which let me believe something is hanging in a undefined state.

Will provide details once I do have them

**Comment by hartkopp** [comment] 2018-12-16 11:12
"module is busy" would only occur when there's still an open socket handled by that module.
Closing this issue for now. Tnx!

**Closed as completed by hartkopp** 2018-12-16 11:12 UTC
